# Generated by Django 3.2.9 on 2022-04-23 23:50

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='actor_image')),
            ],
        ),
        migrations.CreateModel(
            name='Character_Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('actor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.actor')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='director_image')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Non Genre', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('duration', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='movie_image')),
                ('language', models.CharField(default='', max_length=40)),
                ('sinopsis', models.TextField(default='')),
                ('review', models.TextField(default='')),
                ('cinematography', models.FloatField(default=0)),
                ('acting', models.FloatField(default=0)),
                ('editing', models.FloatField(default=0)),
                ('custom', models.FloatField(default=0)),
                ('music', models.FloatField(default=0)),
                ('screenplay', models.FloatField(default=0)),
                ('rotten_tomatoes', models.FloatField(default=0)),
                ('imdb', models.FloatField(default=0)),
                ('actors', models.ManyToManyField(related_name='movies', to='blog.Actor')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.director')),
                ('genres', models.ManyToManyField(to='blog.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scene_Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='scenes_images')),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Quote_Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(blank=True, default='', max_length=100)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.character_movie')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.ForeignKey(default=blog.models.get_default_rating_result, on_delete=django.db.models.deletion.CASCADE, to='blog.rating'),
        ),
        migrations.AddField(
            model_name='character_movie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.movie'),
        ),
        migrations.CreateModel(
            name='Actor_Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Leading Actor', 'Leading Actor'), ('Leading Actress', 'Leading Actress'), ('Supporting Actor', 'Supporting Actor'), ('Supporting Actress', 'Supporting Actress')], default='', max_length=50)),
                ('time_in_movie', models.IntegerField(default=0)),
                ('physical_aspect', models.IntegerField(default=0)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.actor')),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.movie')),
            ],
        ),
    ]
