# Generated by Django 3.2.9 on 2022-04-19 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='actor_image')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='director_image')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('duration', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='movie_image')),
                ('rating_dummy', models.IntegerField(default=0)),
                ('cinematography', models.FloatField(default=0)),
                ('acting', models.FloatField(default=0)),
                ('editing', models.FloatField(default=0)),
                ('custom', models.FloatField(default=0)),
                ('music', models.FloatField(default=0)),
                ('screenplay', models.FloatField(default=0)),
                ('quote1', models.CharField(default='', max_length=100)),
                ('quote2', models.CharField(default='', max_length=100)),
                ('quote3', models.CharField(default='', max_length=100)),
                ('scene1', models.ImageField(blank=True, upload_to='scene_image')),
                ('scene2', models.ImageField(blank=True, upload_to='scene_image')),
                ('scene3', models.ImageField(blank=True, upload_to='scene_image')),
                ('rotten_tomatoes', models.FloatField(default=0)),
                ('imdb', models.FloatField(default=0)),
                ('actors', models.ManyToManyField(related_name='movies', to='blog.Actor')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.director')),
            ],
        ),
    ]
