# Generated by Django 3.2.9 on 2022-04-19 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.IntegerField(default=0),
        ),
    ]
