# Generated by Django 3.2.9 on 2022-04-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_movie_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=100)),
                ('genre_dummy', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=100)),
                ('rating_dummy', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating_dummy',
        ),
        migrations.AddField(
            model_name='movie',
            name='quote1_character',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='quote2_character',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='quote3_character',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='scene1_caption',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='scene2_caption',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='scene3_caption',
            field=models.CharField(default='', max_length=100),
        ),
    ]
