# Generated by Django 3.2.9 on 2022-04-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220424_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='review',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='director',
            name='review',
            field=models.TextField(blank=True, default=''),
        ),
    ]
