# Generated by Django 3.2.9 on 2022-04-20 17:59

import blog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_movie_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.ForeignKey(default=blog.models.get_default_rating_result, on_delete=django.db.models.deletion.CASCADE, to='blog.rating'),
        ),
    ]
