# Generated by Django 3.2.9 on 2022-04-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_movie_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genre_dummy',
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(default='Non Genre', max_length=100),
        ),
    ]
