# Generated by Django 3.2.9 on 2022-04-29 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220427_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='image',
        ),
    ]
