# Generated by Django 3.2.9 on 2022-04-29 03:05

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_actor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='', force_format=None, keep_meta=True, quality=0, size=[150, 200], upload_to='actor_image'),
        ),
    ]
