# Generated by Django 3.2.9 on 2022-04-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_actor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='actor_image'),
        ),
    ]
