# Generated by Django 3.2.9 on 2022-04-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_movie_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='review',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='sinopsis',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='quote1',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='quote1_character',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='quote2',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='quote2_character',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='quote3',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='quote3_character',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='scene1_caption',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='scene2_caption',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='scene3_caption',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
