# Generated by Django 3.2.9 on 2022-05-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_actor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='media/actor_image/ProfilePic.png', upload_to='movie_image'),
        ),
    ]
