# Generated by Django 3.2.9 on 2022-04-22 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_scores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.actor'),
        ),
    ]
