# Generated by Django 3.2.9 on 2022-05-17 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='review_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, default='actor_image/ProfilePic.png', upload_to='movie_image'),
        ),
    ]
