# Generated by Django 3.2.9 on 2022-05-29 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
