# Generated by Django 3.2.9 on 2022-05-29 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0012_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actors', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.actor')),
                ('directors', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.director')),
                ('genres', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.genre')),
                ('movies', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.movie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
