# Generated by Django 3.2.9 on 2022-06-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20220531_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='actors',
        ),
        migrations.AddField(
            model_name='profile',
            name='actors',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Actor'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='directors',
        ),
        migrations.AddField(
            model_name='profile',
            name='directors',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Director'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='genres',
        ),
        migrations.AddField(
            model_name='profile',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Genre'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='movies',
        ),
        migrations.AddField(
            model_name='profile',
            name='movies',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Movie'),
        ),
    ]
