# Generated by Django 3.2.9 on 2022-06-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20220604_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.ImageField(blank=True, default='/media/actor_image/ProfilePic.png', null=True, upload_to='actor_image'),
        ),
    ]
