# Generated by Django 3.2.9 on 2022-06-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_actor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='actors',
            field=models.ManyToManyField(blank=True, to='blog.Actor'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='directors',
            field=models.ManyToManyField(blank=True, to='blog.Director'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='genres',
            field=models.ManyToManyField(blank=True, to='blog.Genre'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='movies',
            field=models.ManyToManyField(blank=True, to='blog.Movie'),
        ),
    ]
