# Generated by Django 3.2.9 on 2022-06-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_actor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='reference_description',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='actor',
            name='reference_image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='director',
            name='image',
            field=models.ImageField(blank=True, default='actor_image/ProfilePic.png', upload_to='director_image'),
        ),
        migrations.AlterField(
            model_name='director',
            name='reference_description',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='director',
            name='reference_image',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='reference_description',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='reference_image',
            field=models.URLField(blank=True, default=''),
        ),
    ]
